stage('Update Deployment File') {
  agent any   // ✅ run outside docker container
  environment {
    GIT_REPO_NAME = "Jenkins-Zero-To-Hero"
    GIT_USER_NAME = "avinashneela"
  }
  steps {
    // ✅ Make sure repo is present on this node workspace
    checkout scm

    withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
      sh """
        set -e
        pwd
        ls -la
        git status

        git config user.email "avinashneela27@gmail.com"
        git config user.name "Avinash"

        sed -i "s/replaceImageTag/${BUILD_NUMBER}/g" Jenkins-Zero-To-Hero-main/java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml

        git add Jenkins-Zero-To-Hero-main/java-maven-sonar-argocd-helm-k8s/spring-boot-app-manifests/deployment.yml
        git commit -m "Update deployment image to version ${BUILD_NUMBER}" || true

        git push https://${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME}.git HEAD:main
      """
    }
  }
}
